services:
  postgres:
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  atlas-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: atlas_dev
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
    ports:
      - 5434:5432
    networks:
      - app-net

volumes:
  pgdata: